const nodemailer = require('nodemailer');
const path = require('path');

require('dotenv').config({ path: path.resolve('.env') });

async function sendEmail(autoGeneratedPassword, employeeEmail, firstname) {
  // create reusable transporter object using the default SMTP transport
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      type: 'OAuth2',
      user: process.env.EMAIL_ADDRESS,
      clientId: process.env.EMAIL_CLIENT_ID,
      clientSecret: process.env.EMAIL_CLIENT_SECRET,
      pass: process.env.EMAIL_PASSWORD,
      refreshToken: process.env.EMAIL_REFRESH_TOKEN,
      accessToken: process.env.EMAIL_ACCESS_TOKEN,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });

  const htmlBody = `
    <h3>Hi there, ${firstname}</h3>
    <h5>Your employee account at Teamwork has been created</h5>
    <p>You may log in using this password ${autoGeneratedPassword}</p>
    <p>To log in, click <a href="#">here</a></p>



    
    <small>Teamwork &bull; Lagos, Nigeria</small>
  `;

  try {
    // send mail with defined transport object
    const info = await transporter.sendMail({
      from: `"Teamwork" <${process.env.EMAIL_ADDRESS}>`, // sender address
      to: employeeEmail, // list of receivers
      subject: 'Employee Account Creation Notification', // Subject line
      text: 'Hello world?', // plain text body
      html: htmlBody, // html body
    });

    return `Message sent: %s ${info.messageId}`;
  } catch (error) {
    return error.message;
  }

  // verify connection configuration
  // transporter.verify((error, success) => {
  //   if (error) {
  //     console.log(error);
  //   } else {
  //     console.log('Server is ready to take our messages');
  //   }
  // });
}

// sendEmail('auto_92y3e', 'eotobo@mun.ca', 'Emmanuel')
//   .then(res => console.log(res))
//   .catch(err => console.log(err));

module.exports = sendEmail;
